<a href="https://colab.research.google.com/github/FarrukhTahir5/python-curriculum/blob/main/Lab_6_EDA%2BSklearn_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data Preparation

*   Feature Scaling
*   Feature Binning
*   Column Transformer
*   Function Transfoerm
*   Sklearn Pipeline

In [31]:
!pip install ydata-profiling
import pandas as pd
from ydata_profiling import ProfileReport

df=pd.read_csv('Titanic-Dataset.csv')

prof = ProfileReport(df)
prof.to_file(output_file='eda.html')


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 12/12 [00:00<00:00, 28.25it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [32]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import FunctionTransformer, OneHotEncoder
from sklearn.pipeline import Pipeline

In [33]:
titanic = pd.read_csv('Titanic-Dataset.csv')

**Feature Scaling**

In [34]:
#Select features for scaling
features_to_scale = ['Age', 'Fare']

In [35]:
# Handle missing values
# Fill missing values in 'Age' and 'Fare' with the median
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].median())
titanic['Fare'] = titanic['Fare'].fillna(titanic['Fare'].median())
#titanic['Age'].fillna(titanic['Age'].median(), inplace=True)
#titanic['Fare'].fillna(titanic['Fare'].median(), inplace=True)

In [36]:
#Apply MinMaxScaler to the selected features
scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(titanic[features_to_scale])
#print(scaled_features)
print(type(scaled_features))

<class 'numpy.ndarray'>


In [37]:

# Convert scaled features into a DataFrame
scaled_df = pd.DataFrame(scaled_features, columns=features_to_scale)
print(scaled_df)


          Age      Fare
0    0.271174  0.014151
1    0.472229  0.139136
2    0.321438  0.015469
3    0.434531  0.103644
4    0.434531  0.015713
..        ...       ...
886  0.334004  0.025374
887  0.233476  0.058556
888  0.346569  0.045771
889  0.321438  0.058556
890  0.396833  0.015127

[891 rows x 2 columns]


In [38]:
#Concatenate the scaled features back into the original DataFrame
print(titanic[features_to_scale])
titanic[features_to_scale] = scaled_df
print(titanic[features_to_scale])
print(type(titanic[features_to_scale]))

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888  28.0  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]
          Age      Fare
0    0.271174  0.014151
1    0.472229  0.139136
2    0.321438  0.015469
3    0.434531  0.103644
4    0.434531  0.015713
..        ...       ...
886  0.334004  0.025374
887  0.233476  0.058556
888  0.346569  0.045771
889  0.321438  0.058556
890  0.396833  0.015127

[891 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>


In [39]:
# Step 6: Display the results
print("After MinMax Scaling:")
print(titanic.shape)
print(titanic.head())

After MinMax Scaling:
(891, 12)
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex       Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  0.271174      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  0.472229      1   
2                             Heikkinen, Miss. Laina  female  0.321438      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  0.434531      1   
4                           Allen, Mr. William Henry    male  0.434531      0   

   Parch            Ticket      Fare Cabin Embarked  
0      0         A/5 21171  0.014151   NaN        S  
1      0          PC 17599  0.139136   C85        C  
2      0  STON/O2. 3101282  0.015469   NaN        S  
3      0            113803  0.103644  C123      

# **Feature Binning**

In [40]:
# Extract Title from Name
titanic['Title'] = titanic['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)
print(titanic['Title'])

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ... 
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: Title, Length: 891, dtype: object


In [41]:
# Define title mapping dictionary
title_mapping = {
    'Mr': 'Mr', 'Mrs': 'Mrs', 'Miss': 'Miss', 'Master': 'Master',
    'Capt': 'Officer', 'Col': 'Officer', 'Major': 'Officer', 'Dr': 'Officer', 'Rev': 'Officer',
    'Countess': 'Royalty', 'Sir': 'Royalty', 'Lady': 'Royalty', 'Jonkheer': 'Royalty', 'Don': 'Royalty',
    'Mlle': 'Miss', 'Ms': 'Miss', 'Mme': 'Mrs'
}
print(type(titanic['Title']))
# Map extracted titles to broader categories & handle unknown titles
titanic['Title_Group'] = titanic['Title'].map(title_mapping)
print(titanic)
#filtered_titanic = titanic[titanic['Title_Group'] == 'Other'].tail(100)
#print(filtered_titanic)

<class 'pandas.core.series.Series'>
     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex       Age  \
0                              Braund, Mr. Owen Harris    male  0.271174   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  0.472229   
2                               Heikkinen, Miss. Laina  female  0.321438   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  0.434531   
4                             Allen, Mr. William Henry    male  0.434531   
..                                                 

In [42]:
# Drop the original 'Title' column (optional)
titanic.drop(columns=['Title'], inplace=True)
print(titanic.head())

# Encode the categorical feature using One-Hot Encoding (optional for ML models)
titanic = pd.get_dummies(titanic, columns=['Title_Group'],  dtype=int)

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex       Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  0.271174      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  0.472229      1   
2                             Heikkinen, Miss. Laina  female  0.321438      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  0.434531      1   
4                           Allen, Mr. William Henry    male  0.434531      0   

   Parch            Ticket      Fare Cabin Embarked Title_Group  
0      0         A/5 21171  0.014151   NaN        S          Mr  
1      0          PC 17599  0.139136   C85        C         Mrs  
2      0  STON/O2. 3101282  0.015469   NaN        S        Miss  
3      0            113803  0.10

In [43]:
# Display the updated dataset with new feature
print(titanic.head())
print(titanic.shape)

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex       Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  0.271174      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  0.472229      1   
2                             Heikkinen, Miss. Laina  female  0.321438      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  0.434531      1   
4                           Allen, Mr. William Henry    male  0.434531      0   

   Parch            Ticket      Fare Cabin Embarked  Title_Group_Master  \
0      0         A/5 21171  0.014151   NaN        S                   0   
1      0          PC 17599  0.139136   C85        C                   0   
2      0  STON/O2. 3101282  0.015469   NaN        S                   0

**Column Transformer**

In [44]:
# Sample DataFrame
data = pd.DataFrame({
    'Age': [22, None, 24, 22, None, 24],
    'Sex': ['male', 'female', 'female','male', 'female', 'female'],
    'Embarked': ['B', 'B', 'C', 'C', 'C','S'],
    'Fare': [7.25, 71.83, 8.05,7.25, 71.83, 8.05]
})

print("Original DataFrame:")
print(data)

# Define ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('age_imputer', SimpleImputer(strategy='mean'), ['Age']),
    ('ohe', OneHotEncoder(), ['Sex','Embarked'])
], remainder='passthrough')  # Pass through other columns like 'Fare'

# Transform the data
transformed_data = preprocessor.fit_transform(data)

# Output shape and transformed data
print("\nTransformed Data Shape:")
print(transformed_data.shape)
#print(type(transformed_data))


transformed_df = pd.DataFrame(transformed_data)
print("\nTransformed DataFrame:")
print(transformed_df)

Original DataFrame:
    Age     Sex Embarked   Fare
0  22.0    male        B   7.25
1   NaN  female        B  71.83
2  24.0  female        C   8.05
3  22.0    male        C   7.25
4   NaN  female        C  71.83
5  24.0  female        S   8.05

Transformed Data Shape:
(6, 7)

Transformed DataFrame:
      0    1    2    3    4    5      6
0  22.0  0.0  1.0  1.0  0.0  0.0   7.25
1  23.0  1.0  0.0  1.0  0.0  0.0  71.83
2  24.0  1.0  0.0  0.0  1.0  0.0   8.05
3  22.0  0.0  1.0  0.0  1.0  0.0   7.25
4  23.0  1.0  0.0  0.0  1.0  0.0  71.83
5  24.0  1.0  0.0  0.0  0.0  1.0   8.05


**Function Transfomer**

In [45]:
# Sample DataFrame
data = pd.DataFrame({
    'Age': [22, None, 24,22, None, 24],
    'Sex': ['male', 'female', 'female','male', 'female', 'female'],
    'Embarked': ['B', 'B', 'C', None, 'C','S'],
    'Fare': [7.25, 71.83, 8.05,7.25, 71.83, 8.05]
})

print("Original DataFrame:")
print(data)

# Custom function to impute 'Embarked'
def impute_embarked(X):
    X['Embarked'] = X['Embarked'].fillna(X['Embarked'].mode()[0])  # Fill missing values
    print(X['Embarked'])
    return X

# Define ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('age_imputer', SimpleImputer(strategy='mean'), ['Age']),
    ('embarked_imputer', FunctionTransformer(impute_embarked), ['Embarked']),
    ('ohe', OneHotEncoder(), ['Sex','Embarked'])
], remainder='passthrough')  # Pass through other columns like 'Fare'

# Transform the data
transformed_data = preprocessor.fit_transform(data)

# Output shape and transformed data
print("\nTransformed Data Shape:")
print(transformed_data.shape)
print(transformed_data)


transformed_df = pd.DataFrame(transformed_data)
print("\nTransformed DataFrame:")
print(transformed_df)


Original DataFrame:
    Age     Sex Embarked   Fare
0  22.0    male        B   7.25
1   NaN  female        B  71.83
2  24.0  female        C   8.05
3  22.0    male     None   7.25
4   NaN  female        C  71.83
5  24.0  female        S   8.05
0    B
1    B
2    C
3    B
4    C
5    S
Name: Embarked, dtype: object

Transformed Data Shape:
(6, 9)
[[22.0 'B' 0.0 1.0 1.0 0.0 0.0 0.0 7.25]
 [23.0 'B' 1.0 0.0 1.0 0.0 0.0 0.0 71.83]
 [24.0 'C' 1.0 0.0 0.0 1.0 0.0 0.0 8.05]
 [22.0 'B' 0.0 1.0 0.0 0.0 0.0 1.0 7.25]
 [23.0 'C' 1.0 0.0 0.0 1.0 0.0 0.0 71.83]
 [24.0 'S' 1.0 0.0 0.0 0.0 1.0 0.0 8.05]]

Transformed DataFrame:
      0  1    2    3    4    5    6    7      8
0  22.0  B  0.0  1.0  1.0  0.0  0.0  0.0   7.25
1  23.0  B  1.0  0.0  1.0  0.0  0.0  0.0  71.83
2  24.0  C  1.0  0.0  0.0  1.0  0.0  0.0   8.05
3  22.0  B  0.0  1.0  0.0  0.0  0.0  1.0   7.25
4  23.0  C  1.0  0.0  0.0  1.0  0.0  0.0  71.83
5  24.0  S  1.0  0.0  0.0  0.0  1.0  0.0   8.05


**Sklean Pipeline**

In [51]:
# Sample DataFrame
data = pd.DataFrame({
    'Age': [22, None, 24,22, None, 24],
    'Sex': ['male', 'female', 'female','male', 'female', 'female'],
    'Embarked': ['B', 'B', 'C', None, 'C','S'],
    'Fare': [7.25, 71.83, 8.05,7.25, 71.83, 8.05]
})

print("Original DataFrame:")
print(data)

# Custom function to impute 'Embarked'
def impute_embarked(X):
    X['Embarked'] = X['Embarked'].fillna(X['Embarked'].mode()[0])  # Fill missing values
    # print (X['Embarked'])
    return X

preprocessor = ColumnTransformer(transformers=[
    ('age_imputer', SimpleImputer(strategy='mean'), ['Age']),
    ('embarked_encoder', Pipeline(steps=[
        ('imputer', FunctionTransformer(impute_embarked)),  # Impute Embarked first
        ('onehot', OneHotEncoder())  # Then apply OneHotEncoder
    ]), ['Embarked']),
    ('ohe', OneHotEncoder(), ['Sex'])
], remainder='passthrough')  # Pass through other columns like 'Fare'


# Transform the data
transformed_data = preprocessor.fit_transform(data)

# Output shape and transformed data
print("\nTransformed Data Shape:")
print(transformed_data.shape)
print(transformed_data)

transformed_df = pd.DataFrame(transformed_data)
print("\nTransformed DataFrame:")
print(transformed_df)


Original DataFrame:
    Age     Sex Embarked   Fare
0  22.0    male        B   7.25
1   NaN  female        B  71.83
2  24.0  female        C   8.05
3  22.0    male     None   7.25
4   NaN  female        C  71.83
5  24.0  female        S   8.05

Transformed Data Shape:
(6, 7)
[[22.    1.    0.    0.    0.    1.    7.25]
 [23.    1.    0.    0.    1.    0.   71.83]
 [24.    0.    1.    0.    1.    0.    8.05]
 [22.    1.    0.    0.    0.    1.    7.25]
 [23.    0.    1.    0.    1.    0.   71.83]
 [24.    0.    0.    1.    1.    0.    8.05]]

Transformed DataFrame:
      0    1    2    3    4    5      6
0  22.0  1.0  0.0  0.0  0.0  1.0   7.25
1  23.0  1.0  0.0  0.0  1.0  0.0  71.83
2  24.0  0.0  1.0  0.0  1.0  0.0   8.05
3  22.0  1.0  0.0  0.0  0.0  1.0   7.25
4  23.0  0.0  1.0  0.0  1.0  0.0  71.83
5  24.0  0.0  0.0  1.0  1.0  0.0   8.05


Apply Feature Creation preprocessing step on the Titanic dataset to create a Family Size feature which calculates Family Size for each Passenger using following Equation. FamilySize = SibSp + Parch + 1

In [47]:
titanic = pd.read_csv('Titanic-Dataset.csv')
def create_family_size(df):
    df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
    return df
titanic.pipe(create_family_size)
print(titanic.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  FamilySize  
0      0         A/5 21171   7.2500   NaN        S           2  
1      0          PC 17599  71.2833   C85        C           2  
2      0  STON/O2. 3101282   7.9250   NaN        S           1  
3      0            113803  53.1000  C123        S          

Apply ColumnTransformer, FunctionTransformer and Sklearn Pipeline on the Titanic dataset.

In [54]:
import re
def increment_alphanumeric(s):
    if pd.isna(s):
        return None

    # Use regular expression to find the numeric part at the end of the string
    match = re.search(r'(\d+)$', s)
    if match:
        numeric_part = match.group(1)
        # Extract the alphanumeric prefix
        prefix = s[:match.start()]
        # Increment the numeric part, maintaining leading zeros and width
        incremented_num = int(numeric_part) + 1
        new_numeric_part = str(incremented_num).zfill(len(numeric_part))
        return f"{prefix}{new_numeric_part}"
    else:
        return s

def custom_ffill_increment(series):
    filled_series = series.copy()
    last_valid_value = None

    for i, value in enumerate(filled_series):
        if pd.notna(value):
            last_valid_value = value
        elif last_valid_value is not None:
            last_valid_value = increment_alphanumeric(last_valid_value)
            filled_series.iloc[i] = last_valid_value

    return filled_series
titanic = pd.read_csv('Titanic-Dataset.csv')
preprocessor = ColumnTransformer(transformers=[
    ('age_imputer', SimpleImputer(strategy='mean'), ['Age']),
    ('embarked_encoder', Pipeline(steps=[
        ('imputer', FunctionTransformer(impute_embarked)),  # Impute Embarked first
        ('onehot', OneHotEncoder())  # Then apply OneHotEncoder
    ]), ['Embarked']),
    ('ohe', OneHotEncoder(), ['Sex']),
    ('Cabin_impute', FunctionTransformer(custom_ffill_increment), ['Cabin'])
], remainder='passthrough')
transformed_data=preprocessor.fit_transform(titanic)
# print("Column Transformer")
print(transformed_data)

[[22.0 0.0 0.0 ... 0 'A/5 21171' 7.25]
 [38.0 1.0 0.0 ... 0 'PC 17599' 71.2833]
 [26.0 0.0 0.0 ... 0 'STON/O2. 3101282' 7.925]
 ...
 [29.69911764705882 0.0 0.0 ... 2 'W./C. 6607' 23.45]
 [26.0 1.0 0.0 ... 0 '111369' 30.0]
 [32.0 0.0 1.0 ... 0 '370376' 7.75]]


In [11]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

heart_ds = pd.read_csv('/content/heart_2022_with_nans.csv')
heart_ds.head()
# prof = ProfileReport(heart_ds)
# prof.to_file(output_file='eda.html')

State     Sex GeneralHealth  PhysicalHealthDays  MentalHealthDays  \
0  Alabama  Female     Very good                 0.0               0.0   
1  Alabama  Female     Excellent                 0.0               0.0   
2  Alabama  Female     Very good                 2.0               3.0   
3  Alabama  Female     Excellent                 0.0               0.0   
4  Alabama  Female          Fair                 2.0               0.0   

                                     LastCheckupTime PhysicalActivities  \
0  Within past year (anytime less than 12 months ...                 No   
1                                                NaN                 No   
2  Within past year (anytime less than 12 months ...                Yes   
3  Within past year (anytime less than 12 months ...                Yes   
4  Within past year (anytime less than 12 months ...                Yes   

   SleepHours RemovedTeeth HadHeartAttack  ... HeightInMeters  \
0         8.0          NaN             No  ...            NaN   
1         6.0          NaN             No  ...           1.60   
2         5.0          NaN             No  ...           1.57   
3         7.0          NaN             No  ...           1.65   
4         9.0          NaN             No  ...           1.57   

  WeightInKilograms    BMI AlcoholDrinkers HIVTesting FluVaxLast12  \
0               NaN    NaN              No         No          Yes   
1             68.04  26.57              No         No           No   
2             63.50  25.61              No         No           No   
3             63.50  23.30              No         No          Yes   
4             53.98  21.77             Yes         No           No   

  PneumoVaxEver                                  TetanusLast10Tdap  \
0            No  Yes, received tetanus shot but not sure what type   
1            No  No, did not receive any tetanus shot in the pa...   
2            No                                                NaN   
3           Yes  No, did not receive any tetanus shot in the pa...   
4           Yes  No, did not receive any tetanus shot in the pa...   

  HighRiskLastYear CovidPos  
0               No       No  
1               No       No  
2               No      Yes  
3               No       No  
4               No       No  

[5 rows x 40 columns]

In [25]:
# remove duplicates
df_no_duplicates = heart_ds.drop_duplicates()

In [13]:
df_no_duplicates['LastCheckupTime'].unique()

array(['Within past year (anytime less than 12 months ago)', nan,
       'Within past 2 years (1 year but less than 2 years ago)',
       'Within past 5 years (2 years but less than 5 years ago)',
       '5 or more years ago'], dtype=object)

In [27]:
def impute_general_health(df):
    df['GeneralHealth'] = df['GeneralHealth'].fillna(df['GeneralHealth'].mode()[0])
    return df
preprocessor = ColumnTransformer(transformers=[
    ('general_health_encoder', Pipeline(steps=[
        ('imputer', FunctionTransformer(impute_general_health)),  # Impute Embarked first
        ('onehot', OneHotEncoder(sparse_output=False))  # Then apply OneHotEncoder
    ]),['GeneralHealth']),
    ('LastCheckupTime_encoder',OneHotEncoder(sparse_output=False), ['LastCheckupTime']),
    ('ohe', OneHotEncoder(sparse_output=False), ['Sex'])
], remainder='passthrough')  # Pass through other columns like 'Fare'
preprocessor.set_output(transform="pandas") # This is key for DataFrame output

pipeline = Pipeline(steps=[('preprocessor', preprocessor)])
pipeline.set_output(transform="pandas")
transformed_data = pipeline.fit_transform(df_no_duplicates)

In [29]:
transformed_data.head()

general_health_encoder__GeneralHealth_Excellent  \
0                                              0.0   
1                                              1.0   
2                                              0.0   
3                                              1.0   
4                                              0.0   

   general_health_encoder__GeneralHealth_Fair  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         1.0   

   general_health_encoder__GeneralHealth_Good  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   general_health_encoder__GeneralHealth_Poor  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   general_health_encoder__GeneralHealth_Very good  \
0                                              1.0   
1                                              0.0   
2                                              1.0   
3                                              0.0   
4                                              0.0   

   LastCheckupTime_encoder__LastCheckupTime_5 or more years ago  \
0                                                0.0              
1                                                0.0              
2                                                0.0              
3                                                0.0              
4                                                0.0              

   LastCheckupTime_encoder__LastCheckupTime_Within past 2 years (1 year but less than 2 years ago)  \
0                                                0.0                                                 
1                                                0.0                                                 
2                                                0.0                                                 
3                                                0.0                                                 
4                                                0.0                                                 

   LastCheckupTime_encoder__LastCheckupTime_Within past 5 years (2 years but less than 5 years ago)  \
0                                                0.0                                                  
1                                                0.0                                                  
2                                                0.0                                                  
3                                                0.0                                                  
4                                                0.0                                                  

   LastCheckupTime_encoder__LastCheckupTime_Within past year (anytime less than 12 months ago)  \
0                                                1.0                                             
1                                                0.0                                             
2                                                1.0                                             
3                                                1.0                                             
4                                                1.0                                             

   LastCheckupTime_encoder__LastCheckupTime_nan  ...  \
0                                           0.0  ...   
1                                           1.0  ...   
2                                           0.0  ...   
3                   

In [21]:
 df_1d = pd.DataFrame(transformed_data)

In [22]:
df_1d.head()

0    1    2    3    4    5    6    7    8    9   ...    39     40     41  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...   NaN    NaN    NaN   
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   1.6  68.04  26.57   
2  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  1.57   63.5  25.61   
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.65   63.5   23.3   
4  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.57  53.98  21.77   

    42  43   44   45                                                 46  47  \
0   No  No  Yes   No  Yes, received tetanus shot but not sure what type  No   
1   No  No   No   No  No, did not receive any tetanus shot in the pa...  No   
2   No  No   No   No                                                NaN  No   
3   No  No  Yes  Yes  No, did not receive any tetanus shot in the pa...  No   
4  Yes  No   No  Yes  No, did not receive any tetanus shot in the pa...  No   

    48  
0   No  
1   No  
2  Yes  
3   No  
4   No  

[5 rows x 49 columns]

# Lab Task

**Apply Feature Creation preprocessing step on the Titanic dataset to create a Family Size feature which calculates Family Size for each Passenger using following Equation. FamilySize = SibSp + Parch + 1**

**Apply ColumnTransformer, FunctionTransformer and Sklearn Pipeline on the Titanic dataset.**

**Use ColumnTransformer, FunctionTransformer and Sklearn Pipeline features to preprocess the following dataset**

https://www.kaggle.com/datasets/kamilpytlak/personal-key-indicators-of-heart-disease